[[resources-receiving-order]]
== ReceivingOrder
A `ReceivingOrder` represents an announcement of goods the are expected to be received at the warehouse. Usually these kind of orders are
sent by the ERP system prior to the actual physical goods receipt. A `ReceivingOrder` is just the envelope that contains
`ReceivingOrderPositions`, where each position determines the expected product and a quantity.

=== ReceivingOrder Index
The index with all possible operations on a `ReceivingOrder` can be retrieved with a GET request:

include::{generated}/get-order-index/http-request.adoc[]

The response lists all the operations possible on `ReceivingOrders` with a name and the corresponding href link:

include::{generated}/get-order-index/http-response.adoc[]

=== Create a ReceivingOrder
The `POST` operation takes a flat structure of a simple `ReceivingOrder` to create.

include::{generated}/order-create/http-request.adoc[]
include::{generated}/order-create/request-fields.adoc[]

If the `ReceivingOrder` has been created successfully, the server returns the URI to the created resource in the `Location` header:

include::{generated}/order-create/http-response.adoc[]

In case the client request did not match the server expectations because of invalid or missing fields in the request body, the server
responds with:

include::{generated}/order-create-400/http-response.adoc[]

[[resources-receiving-order-find]]
=== Find a ReceivingOrder by Persistent Key
A HTTP `GET request is required to lookup a `ReceivingOrder` by its synthetic persistent key.

include::{generated}/order-find/http-request.adoc[]

If the `ReceivingOrder` has been found, the server returns the order instance in the response body:

include::{generated}/order-find/http-response.adoc[]
include::{generated}/order-find/response-fields.adoc[]

In case the order does not exist, the server responds with a error of the 4xx-client family because the `pKey` is expected to exist:

include::{generated}/order-find-404/http-response.adoc[]

[[resources-receiving-order-findby-orderid]]
=== Find a ReceivingOrder by Order ID
A HTTP `GET` request is required to find a `ReceivingOrder` by it's identifying business key, the order ID.

include::{generated}/order-findby-orderid/http-request.adoc[]

If the `ReceivingOrder` has been found, the server returns the order instance in the response body:

include::{generated}/order-findby-orderid/http-response.adoc[]

In case the order does not exist, the server responds in the same way like <<resources-receiving-order-find>>.

[[resources-receiving-order-findall]]
=== Find all ReceivingOrders
A HTTP `GET request to the primary resource is required to find all `ReceivingOrders`. Notice, this method is foreseen for UI applications
and may change in future API versions.

include::{generated}/order-find-all/http-request.adoc[]

Returns an array of `ReceivingOrders` or an empty array:

include::{generated}/order-find-all/http-response.adoc[]

[[resources-receiving-order-cancel]]
=== Cancel a ReceivingOrder
An earlier created `ReceivingOrder` can be cancelled for further processing. The client needs to send a HTTP `DELETE request with the
unique identifier of the order.

include::{generated}/order-cancel/http-request.adoc[]

If the `ReceivingOrder` has been cancelled, the server returns with:

include::{generated}/order-cancel/http-response.adoc[]

In case the order couldn't be cancelled because the order is already in process or has been processed, the server responds with:

include::{generated}/order-cancel-403/http-response.adoc[]

[[resources-receiving-order-capture]]
=== Capture a Receiving
When products arrive at the warehouse they are usually announced with a `ReceivingOrder` and its `ReceivingOrderPositions` beforehand. This
is called an expected receipt. Also unexpected receipts may occur, any unplanned material that needs to be stored in the warehouse without
any previously received order information. Unexpected receipts may also happen as part of an expected receipt when a supplier ships more of
a product that was previously announced in a `ReceivingOrderPosition`. Multiple capturing types exists:

- Expected `Product` are captured on a `LoadUnit`
- Expected `Product` are captured on a `Location`
- Expected `TransportUnits` without `Product` information are captured on a `Location`

The capturing process happens at the Goods In area of the warehouse, where material arrives and is identified (captured). The identified
articles or `TransportUnits` are assigned to `ReceivingOrderPositions`.

==== Capture an expected Product on a LoadUnit
The received `Product` is identified and assigned to an existing `ReceivingOrderPosition`. As part of the capturing process the items are
basically placed on a `LoadUnit` on top of a `TransportUnit`.

To capture an amount of a `Product` in the context of a `ReceivingOrder` the caller sends a `POST` request to the server with the
identifying `pKey` of the `ReceivingOrder` as part of the URI:

include::{generated}/order-capture/http-request.adoc[]
include::{generated}/order-capture/request-fields.adoc[]

If an open and not satisfied `ReceivingOrderPosition` with the captured `Product` exists the captured quantity is assigned to that position
and the items are booked to the `LoadUnit` on top of the `TransportUnit. The server responds with success:

include::{generated}/order-capture/http-response.adoc[]

If no open `ReceivingOrderPosition` exists in the `ReceivingOrder` or the `Product` does not fit to the list of expected `Products` and
overbooking an expected `ReceivingOrderPosition` is not allowed, the server does not allow to receive the goods and responds with an error:

include::{generated}/order-capture-to-many/http-response.adoc[]

*Overbooking* means: The Receiving Service allows `Overbooking` or not. In case `Overbooking` is allowed, the supplier can ship a higher
quantity than previously announced in the `ReceivingOrderPosition`. If `Overbooking` is forbidden, the server raises an exception in case of
more is received than expected. This setting is currently configured service wide and not per `Product`.

==== Capture an expected Product on a Location
The received `Product` is identified and assigned to an existing `ReceivingOrderPosition`. As part of the capturing process the items are
placed on a `Location` directly without any carrier like a `LoadUnit` or a `TransportUnit`.

To capture an amount of a `Product` in the context of a `ReceivingOrder` the caller sends a `POST` request to the server with the
identifying `pKey` of the `ReceivingOrder` as part of the URI:

include::{generated}/order-capture-loc/http-request.adoc[]
include::{generated}/order-capture-loc/request-fields.adoc[]

If an open and not satisfied `ReceivingOrderPosition` with the captured `Product` exists the captured quantity is assigned to that position
and the items are booked directly onto the given `Location`. The server responds with success:

include::{generated}/order-capture-loc/http-response.adoc[]

If no open `ReceivingOrderPosition` exists in the `ReceivingOrder` or the `Product` does not fit to the list of expected `Products`, the
server does not allow to receive the article and responds with an error:

include::{generated}/order-capture-loc-to-many/http-response.adoc[]

==== Capture an expected TransportUnit on a Location
It may happen that an external supplier ships back existing and empty `TransportUnits` to the warehouse. In this case, the announced
`ReceivingOrder` contains `ReceivingOrderPositions` that point to the expected `TransportUnit`.

To capture an received `TransportUnit` the operator identifies (e.g. scans) the `TransportUnit` and the `LoadUnit` on top (optional) and the
client device sends a `POST` request to the server with the identifying `pKey` of the `ReceivingOrder` as part of the URI:

include::{generated}/order-capture-tu/http-request.adoc[]
include::{generated}/order-capture/request-fields.adoc[]

If an open and not satisfied position with the expected `TransportUnit` exists the server responds with success and the state of the
`ReceivingOrderPosition` changes to `COMPLETED`:

include::{generated}/order-capture-tu/http-response.adoc[]

If no open `ReceivingOrderPosition` with the captured `TransportUnit` exists in the `ReceivingOrder`, the server does not allow to receive
the `TransportUnit` and responds with an error:

include::{generated}/order-capture-tu-unexpected/http-response.adoc[]
