[[resources-receiving-order]]
== ReceivingOrder
A `ReceivingOrder` represents an announcement of goods the are expected to be received at the warehouse. Usually these kind of orders are
sent by the ERP system prior to the actual physical goods receipt. A `ReceivingOrder` is just the envelope that contains
`ReceivingOrderPositions`, where each position determines the expected product and a quantity.

=== ReceivingOrder Index
The index with all possible operations on a `ReceivingOrder` can be retrieved with a GET request:

include::{generated}/get-order-index/http-request.adoc[]

The response lists all the operations possible on `ReceivingOrders` with a name and the corresponding href link:

include::{generated}/get-order-index/http-response.adoc[]

=== Create a ReceivingOrder
The `POST` operation takes a flat structure of a simple `ReceivingOrder` to create.

include::{generated}/order-create/http-request.adoc[]
include::{generated}/order-create/request-fields.adoc[]

If the `ReceivingOrder` has been created successfully, the server returns the URI to the created resource in the `Location` header:

include::{generated}/order-create/http-response.adoc[]

In case the client request did not match the server expectations because of invalid or missing fields in the request body, the server
responds with:
include::{generated}/order-create-400/http-response.adoc[]

[[resources-receiving-order-find]]
=== Find a ReceivingOrder by Persistent Key
A HTTP `GET request is required to lookup a `ReceivingOrder` by its synthetic persistent key.

include::{generated}/order-find/http-request.adoc[]

If the `ReceivingOrder` has been found, the server returns the order instance in the response body:

include::{generated}/order-find/http-response.adoc[]
include::{generated}/order-find/response-fields.adoc[]

In case the order does not exist, the server responds with a error of the 4xx-client family because the `pKey` is expected to exist:

include::{generated}/order-find-404/http-response.adoc[]

[[resources-receiving-order-findby-orderid]]
=== Find a ReceivingOrder by Order ID
A HTTP `GET` request is required to find a `ReceivingOrder` by it's identifying business key, the order ID.

include::{generated}/order-findby-orderid/http-request.adoc[]

If the `ReceivingOrder` has been found, the server returns the order instance in the response body:

include::{generated}/order-findby-orderid/http-response.adoc[]

In case the order does not exist, the server responds in the same way like <<resources-receiving-order-find>>.

[[resources-receiving-order-findall]]
=== Find all ReceivingOrders
A HTTP `GET request to the primary resource is required to find all `ReceivingOrders`. Notice, this method is foreseen for UI applications
and may change in future API versions.

include::{generated}/order-find-all/http-request.adoc[]

Returns an array of `ReceivingOrders` or an empty array:

include::{generated}/order-find-all/http-response.adoc[]

[[resources-receiving-order-cancel]]
=== Cancel a ReceivingOrder
An earlier created `ReceivingOrder` can be cancelled for further processing. The client needs to send a HTTP `DELETE request with the
unique identifier of the order.

include::{generated}/order-cancel/http-request.adoc[]

If the `ReceivingOrder` has been cancelled, the server returns with:

include::{generated}/order-cancel/http-response.adoc[]

In case the order couldn't be cancelled because the order is already in process or has been processed, the server responds with:

include::{generated}/order-cancel-403/http-response.adoc[]

[[resources-receiving-order-capture]]
=== Receiving Goods
When products arrive at the warehouse they are usually announced with a `ReceivingOrder` and its `ReceivingOrderPositions` beforehand. This
is called an expected receipt. Also unexpected receipts may occur, any unplanned material that needs to be stored in the warehouse without
any previous received order information. Unexpected receipts may also happen as part of an expected receipt when a supplier ships more items
than previously announced in a `ReceivingOrderPosition`. Multiple types of capturing exists for expected and blind receipts:

- A `Product` is captured on a `LoadUnit`
- A `Product` is captured on a `Location`
- A `TransportUnit` without `Product` information is captured on a `Location`

The capturing process happens at the Goods In area of the warehouse, where material arrives and is identified (captured or recorded). In
case of expected receipts, the identified items or `TransportUnits` are assigned to `ReceivingOrderPositions`.

The default capturing implementation can be configured with custom capturing approval rules that validate each `ReceivingOrderPosition`
before capturing to prohibit the process. An example can be found in the section <<Expected Receipt: Capture an expected Product on a Location>>

[[resources-receiving-order-capture-p-in-lu]]
==== Expected Receipt: Capture a Product in a LoadUnit
The received `Product` is identified and assigned to an existing `ReceivingOrderPosition`. As part of the capturing process the items are
basically placed in a `LoadUnit` on top of a `TransportUnit`.

To capture the amount of a `Product` in the context of a `ReceivingOrder` the caller sends a `POST` request to the server with the
identifying `pKey` of the `ReceivingOrder` as part of the URI:
include::{generated}/order-capture/http-request.adoc[]
include::{generated}/order-capture/request-fields.adoc[]

If an open and not satisfied `ReceivingOrderPosition` with the captured `Product` exists the captured quantity is assigned to that position
and the items are created in the `LoadUnit` on top of the `TransportUnit. The server responds with the updated `ReceivingOrder` instance:
include::{generated}/order-capture/http-response.adoc[]

If no open `ReceivingOrderPosition` exists in the `ReceivingOrder` or the `Product` does match the list of expected `Products` and
overbooking of that kind of `Product` is not allowed, the server prohibits the goods receipt and responds with an error:
include::{generated}/order-capture-to-many/http-response.adoc[]

*Overbooking* means: In case `Overbooking` is allowed for a `Product`, the supplier can ship a higher amount of that `Product` than
previously announced in the `ReceivingOrderPosition`. If `Overbooking` is forbidden, the server raises an exception. Overbooking can be
configured per `Product`.

[[resources-receiving-order-capture-p-on-loc]]
==== Expected Receipt: Capture an expected Product on a Location
The received `Product` is identified and assigned to an existing `ReceivingOrderPosition`. As part of the capturing process the items are
placed on a `Location` directly without any carrier like a `LoadUnit` or a `TransportUnit`.

To capture the amount of a `Product` in the context of a `ReceivingOrder` the caller sends a `POST` request to the server with the
identifying `pKey` of the `ReceivingOrder` as part of the URI:
include::{generated}/order-capture-loc/http-request.adoc[]
include::{generated}/order-capture-loc/request-fields.adoc[]

If an open and not satisfied `ReceivingOrderPosition` with the captured `Product` exists the captured quantity is assigned to that position
and the items are directly placed onto the given `Location`. The server responds with the updated `ReceivingOrder` instance:
include::{generated}/order-capture-loc/http-response.adoc[]

If no open `ReceivingOrderPosition` exists in the `ReceivingOrder` or the `Product` does not fit to the list of expected `Products`, the
server prohibits the goods receipt and responds with an error:
include::{generated}/order-capture-loc-to-many/http-response.adoc[]

If a custom `CapturingApproval` is registered that validates the `ReceivingOrderPosition` and prohibits the capturing process, the server
responds with:
include::{generated}/order-capture-loc-403/http-response.adoc[]

[[resources-receiving-order-capture-tu-on-loc]]
==== Expected Receipt: Capture an expected TransportUnit on a Location
It may happen that an external supplier ships back existing `TransportUnits` to the warehouse. In this case, the announced `ReceivingOrder`
contains `ReceivingOrderPositions` that point to the expected `TransportUnit`.

To capture the received `TransportUnit` the operator identifies (e.g. scans) the `TransportUnit` and the `LoadUnit` on top (optional) and
the client device sends a `POST` request to the server with the identifying `pKey` of the `ReceivingOrder` as part of the URI:
include::{generated}/order-capture-tu/http-request.adoc[]
include::{generated}/order-capture/request-fields.adoc[]

If an open and not satisfied position with the expected `TransportUnit` exists the `ReceivingOrderPosition` is completely captured, means
all expected items are created, the state of the `ReceivingOrderPosition` has changed to `COMPLETED` and the server responds with the
updated `ReceivingOrder` instance:
include::{generated}/order-capture-tu/http-response.adoc[]

If no open `ReceivingOrderPosition` with the captured `TransportUnit` in the `ReceivingOrder` exists, the server prohibits the receipt of
the `TransportUnit` and responds with an error:
include::{generated}/order-capture-tu-unexpected/http-response.adoc[]

[[resources-receiving-order-captureb-p-in-lu]]
==== Blind Receipt: Capture a Product in a LoadUnit
Items of a `Product` are received, without any ASN (Advanced Shipping Notice). Therefor this receipt cannot be captured and validated
against a `ReceivingOrder`. The received items are created and put into a `LoadUnit` on top of a `TransportUnit`.

Similar to an expected receipt the caller sends a `POST` request to the server but without any `ReceivingOrder` reference in the URI:
include::{generated}/br-lu-capture/http-request.adoc[]
include::{generated}/br-lu-capture/request-fields.adoc[]

If successful the server responds with:
include::{generated}/br-lu-capture/http-response.adoc[]

[[resources-receiving-order-captureb-p-on-loc]]
==== Blind Receipt: Capture a Product on a Location
Items of a `Product` are received, without any ASN (Advanced Shipping Notice). Therefor this receipt cannot be captured and validated
against a `ReceivingOrder`. The received items are placed on a `Location` directly without any carrier like a `LoadUnit` or a `TransportUnit`.

Similar to an expected receipt the caller sends a `POST` request to the server but without any `ReceivingOrder` reference reference in the
URI:
include::{generated}/br-loc-capture/http-request.adoc[]
include::{generated}/br-loc-capture/request-fields.adoc[]

If successful the server responds with:
include::{generated}/br-loc-capture/http-response.adoc[]

[[resources-receiving-order-captureb-tu-on-loc]]
==== Blind Receipt: Capture an unexpected TransportUnit on a Location
It may happen that an external supplier ships back empty `TransportUnits` to the warehouse without any ASN (Advanced Shipping Notice)
information. To capture and create those `TransportUnits` in the system the identifier, type and current `Location` of the `TransportUnit`
must be passed to the API.

The client device sends a `POST` request to the server with the mandatory `TransportUnit` data in the request body:
include::{generated}/br-tu-capture/http-request.adoc[]
include::{generated}/br-tu-capture/request-fields.adoc[]

If the `TransportUnit` has been created successfully the server responds with:
include::{generated}/br-tu-capture/http-response.adoc[]
