#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin https://registry.butan092.startdedicated.de
docker push registry.butan092.startdedicated.de/interface21.io/org.openwms.wms.receiving:latest
